www/assets/css/style.css
www/newsletter_confirm.html
www/newsletter_thankyou.html

added the two pages to replace the default mailchimp confirmation pages - trackes only on ?confirmed=yes:
http://kittiebots.us3.list-manage.com/subscribe/post?u=ccc4b9448a982cacc6429f42f&id=c5c8a04f03
http://jewelbots.us3.list-manage1.com/subscribe/confirm?u=ccc4b9448a982cacc6429f42f&id=c5c8a04f03&e=e4a5a3750e

adding custom mailchimp confirmation pages

---

static/scss/style.scss

incorporeted Sara's feedback to hide the copy over hero badge

updated hero to hide copy over kickstarter badge

---

static/html/index.hbs

Updated the quote to make it more impacting.

updated press quote on site to make it more interesting

---

static/js/site-scripts.js

deactivating newsletter popup modal on WWW to focus on sales CTA

deactivating newsletter modal on scroll down to focus on presale CTA

---

static/html/about.hbs
static/html/contact.hbs
static/html/filename.hbs
static/html/index.hbs

added twitter tracking to main pages

added twitter conversion snippet

---

static/html/index.hbs
static/js/site-scripts.js
static/scss/style.scss

- new mixpanel events on modal
- header shorter to surface product section

making header smaller, adding new events to mixpannel

---

static/html/404.hbs
static/html/about.hbs
static/html/contact.hbs
static/html/index.hbs
static/html/newsletter_thankyou.hbs
static/js/site-scripts.js
static/scss/style.scss

- removed shopify from www.jewelbots.com
- added hard coded links to bypass cart and proceed directly to checkout
- fixed 404 bug after newsletter subscription

bypass cart on www. and fixed bug on news-letter

---

static/html/about.hbs
static/html/contact.hbs
static/html/index.hbs
static/js/site-scripts.js

- model removed
- mixpanel tracks from for newsletter conversion in order for us to see 1) subscribe newsletter / 2) got newsletter / 3) bought something funnel later

updated modal and mixpanel

---

static/html/index.hbs

- spelling mistake "fist" --> "first"

fix spelling of CTA

---

static/html/index.hbs

- making sure we only test the two taglines:
Smart Programmable Friendship Bracelets
Smart Jewelry  for a Smarter Generation

final changes to AB test

---

static/html/index.hbs

- we are starting to track people who looked at the site but did not order --> will hit them on facebook with ads

adding facebook retageting pixel on homepage

---

static/html/index.hbs
static/js/site-scripts.js
static/scss/style.scss

- initial styling
- reading the latest 10 tweets '@jewelbots' and rotates them every 5s

adding twitter feed v1 to homepage

---

static/html/about.hbs
static/html/contact.hbs
static/html/index.hbs
static/js/site-scripts.js
static/scss/style-reset.scss
static/scss/style.scss

- added modal back in as per Sara's request (only after scrolling to bottom)
- A/B test for old and enhanced pre-sale flow
- fixed a bug with empty cart and direct checkout

A/B test for updated cart pre-sale flow

---

static/html/about.hbs

- removing comments from old merge conflict

fixing merge issue on about page

---

static/html/about.hbs
static/html/contact.hbs

- copy and paste error which tracks about and contact page as HOME

wrong page names on ABOUT / Contact pages

---

static/html/index.hbs
static/js/site-scripts.js

- removing preloader to reduce friction

removing preloader from homepage

---

static/html/index.hbs

- anchor tag was breaking for version B of A/B test

fixing bug with scrolling for AB test

---

static/html/about.hbs

- Scott moved forward in time and almost saw himself in the future, we needed to send him back.

removing Scott to prevent a devastating time paradox

---

static/html/index.hbs
static/html/newsletter_thankyou.hbs

- taking out old facebook pixels
- adding new ones
- adding optimizely snippet

adding facebook conversion pixel for large media

---

static/html/index.hbs

adding google analytics to homepage

---

static/html/index.hbs
static/js/site-scripts_v5.js
static/scss/style_v5.css

- fixing mobile hero
- adding CTA to direct people to Ambassador Homepage

adding note for ambassador page

---

static/html/index.hbs

- added a tracking pixel for the new referral program

adding tracking pixel for InviteReferrals

---

static/html/index.hbs
static/scss/style-reset.scss

- reactivating original Jewelbots Prices.

activating old prices

---

static/html/index.hbs
static/scss/style_v5.css

updated styles for xmas special

---

static/html/index.hbs
static/html/intro-to-wearables-kit.hbs

- removing xmas special (order now to ship before XMAS)
- add intro to wearables placeholder page

added intro to wearables page placeholder

---

static/html/index.hbs

- removing last traces for 18th Xmas copy

updated copy

---

static/html/index.hbs

Removed space from single Jewelbot price.

---

static/html/index.hbs

- adding code for adroll retargeting

Optimization

---

static/html/index.hbs

- removing direct link to wearables kit in order to promote 3-pack was confusing to some customers
- added back in

adding buy button for wearables kit back in

---

static/html/index.hbs

- old referral program not in sync with the new wearables plan
- removed until we have an updated campaign

removing invite referrals from homepage

---

static/html/index.hbs

- hero tagline: adding s to kid --> changing it to kids

copy change hero

---

static/html/index.hbs
static/html/newsletter_thankyou.hbs
static/scss/style.scss

- added new copt for discount code on newsletter confirmation page
- fixed a bug with a not tracking link in mixpanel
- hiding the modal from users who just subscribed

including the new onboarding email workflow

---

static/html/become-an-ambassador.hbs
static/html/contact.hbs
static/html/jobs.hbs
static/html/privacy.hbs

Fixed section_copy issues
Fixed support email address to use correct support email that's trackable.

Fixing bugs

---

static/html/index.hbs
static/js/site-scripts.js
static/scss/style.scss

- replacing $10 discount cta with news cta

adding a defferent cta for newsletter subscriptions

---

static/html/index.hbs
static/scss/style.scss

implementing winner of hero A/B test

---

static/html/index.hbs

Updating website text. [[selfie-0 uploading...]]

Text change

---

static/html/index.hbs

updating counter

---

static/html/index.hbs

- BESTIE 3-pack becomes SQUAD 3-pack

updating 3-pack name

---

static/html/index.hbs
static/scss/style.scss

- counter 821
- pre-sale note added back in

updating counter and pre-sale note

---

static/html/index.hbs
static/scss/style.scss

- updated counter
- counter to iframe to reduce pull requests

- counter to iframe

---

static/html/index.hbs
static/js/site-scripts.js

- creates user profiles and merges them with shopify data
- added new funnel to prevent timeout

updating mixpanel to track individual user profiles from shopify

---

static/html/index.hbs

- adding custom facebook pixel to our website
- only tracks (www_home) as in mixpanel
- allows us to retarget leads to our homepage

adding custom facbook pixel to our homepage

---

static/html/index.hbs

- added content category and conversion value

adding content category to facebook pixel to retarget leads

---

static/html/404.hbs
static/html/about.hbs
static/html/become-an-ambassador.hbs
static/html/contact.hbs
static/html/index.hbs
static/html/intro-to-wearables-kit.hbs
static/html/jobs.hbs
static/html/newsletter_thankyou.hbs
static/html/privacy.hbs

- added pixel to remaining pages

adding facebook pixel to all pages on website

---

static/html/index.hbs
static/js/site-scripts.js

- header anchor tags not working
- updated counter to 315

fixing anchor tags

---

static/html/index.hbs

- video would play outside of visible browser window

fixing video playback bug on smaller screens

---

static/html/index.hbs
static/scss/style.scss

- top counter back to iframe so counts can be adjusted for campaign

counter to iframe

---

static/html/index.hbs
static/scss/style.scss

- testing current direct checkout vs on page cart
- attempt to decrease number in cart abandonment

new A/B test T_10

---

static/html/index.hbs

- feedback from growth meeting 06/08/2016

change copy on sale section from 'add to cart' to 'buy now'

---

static/html/buy2.hbs
static/html/index.hbs

no newsletter modal when leaving the landingpage A/B

removing modal prompt for newsletter

---

static/html/buy2.hbs
static/html/index.hbs

- countdown removed from top of both landingpages

removing counter from both landingpages

---

static/html/buy2.hbs
static/scss/style.scss

- bug: newsletter modal placed fixed in the middle of the screen on devices with less than 768px width
- fixed positioning to place it back on top

fixing bug on mobile which prevents newsletter form to filled out

---

static/html/buy2.hbs
static/html/index.hbs

updating shipping prices

---

static/html/index.hbs

- logo on homepage would link to buy2.html
- fixed so it links to homepage

fixing bug in homepage navigation

---

static/html/index.hbs

- index.html
- no further reference of "visual programming language"

removing the phrases around visual programming language

---

static/html/index.hbs

- removed section with old jewelbots box content on site

remove image of package contents

---

static/html/buy2.hbs
static/html/index.hbs

- updated "late summer" to "late autumn" to reflect new shipping timeline

updating shipping date to autumn
